dotenv: .env
wallets:
  from_key: ${PRIVATE_KEY}
dependencies:
  - smartcontractkit/chainlink-brownie-contracts@1.1.1
compiler:
  solc:
    remappings:
      - '@chainlink=smartcontractkit/chainlink-brownie-contracts@1.1.1'
networks:
  default: development
  rinkeby:
    eth_usd_price_feed_address: '0x8A753747A1FA494EC906CE90E9F37563A8AF630E'
    verfiy: True
  mainnet-fork-dev:
    eth_usd_price_feed_address: '0x5f4eC3Df9cbd43714FE2740f5E3616155c5b8419'
    verfiy: False
  development:
    verify: False
  ganache-local:
    verify: False